GitHub-CI/build_Mono-5_18: don't install apt-transport-https
Debian strech does not have apt-transport-https so we can't install it.
Not installing it should fix the build error:

	E: Unable to locate package apt-transport-https
	Error: Process completed with exit code 100.