GitHub-CI: add APT source detection to aid debugging
build_Mono-5_18 fails in a weird way:

	Run apt update > /dev/null || true # ignore exit code so mixed HTTP and

	WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

	E: The method driver /usr/lib/apt/methods/https could not be found.
	E: The repository 'http://security.debian.org/debian-security stretch/updates Release' does not have a Release file.
	E: The repository 'http://deb.debian.org/debian stretch Release' does not have a Release file.
	E: The repository 'http://deb.debian.org/debian stretch-updates Release' does not have a Release file.

	WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

	E: Unable to locate package apt-transport-https
	Error: Process completed with exit code 100.

So we dump all APT source entries: