Travis-CI, Frontend-GNOME.csproj: remove indicate-sharp to fix CI build
Travis has changed the build environment for "language: C" from precise to
trusty and now the build fails like this:

    Project "/home/travis/build/meebey/smuxi/src/Frontend-GNOME/Frontend-GNOME.csproj" (default target(s)):
    ...
	Tool /usr/bin/mcs execution started with arguments: /noconfig /codepage:65001 /debug:full /debug+ /optimize+ /out:obj/Release/smuxi-frontend-gnome.exe /resource:obj/Release/Smuxi.Frontend.Gnome.smuxi-frontend-gnome.glade,smuxi-frontend-gnome.glade /resource:obj/Release/Smuxi.Frontend.Gnome.gtk-gui.gui.stetic,gui.stetic /resource:obj/Release/Smuxi.Frontend.Gnome.images.icon_256x256.png,icon_256x256.png /resource:obj/Release/Smuxi.Frontend.Gnome.images.group-chat_256x256.png,group-chat_256x256.png /resource:obj/Release/Smuxi.Frontend.Gnome.images.person-chat_256x256.png,person-chat_256x256.png /resource:obj/Release/Smuxi.Frontend.Gnome.images.protocol-chat_256x256.png,protocol-chat_256x256.png /resource:obj/Release/Smuxi.Frontend.Gnome.images.session-chat_256x256.png,session-chat_256x256.png AboutDialog.cs AssemblyInfo.cs CrashDialog.cs EngineManagerDialog.cs Entry.cs Frontend.cs GnomeUI.cs Main.cs MainWindow.cs NotImplementedMessageDialog.cs Notebook.cs SplashScreenWindow.cs ChatViewManager.cs Preferences/ServerListView.cs Preferences/PreferencesDialog.cs gtk-gui/generated.cs QuickConnectDialog.cs SteticPreferencesDialog.cs gtk-gui/Smuxi.Frontend.Gnome.SteticPreferencesDialog.cs gtk-gui/Smuxi.Frontend.Gnome.QuickConnectDialog.cs FindGroupChatDialog.cs gtk-gui/Smuxi.Frontend.Gnome.FindGroupChatDialog.cs ../AssemblyVersion.cs ChatFindDialog.cs gtk-gui/Smuxi.Frontend.Gnome.ChatFindDialog.cs Views/Chats/ChatView.cs Views/Chats/GroupChatView.cs Views/Chats/PersonChatView.cs Views/Chats/ProtocolChatView.cs Views/Chats/SessionChatView.cs Views/MessageTextView.cs OpenChatDialog.cs gtk-gui/Smuxi.Frontend.Gnome.OpenChatDialog.cs ChatTypeWidget.cs gtk-gui/Smuxi.Frontend.Gnome.ChatTypeWidget.cs gtk-gui/Smuxi.Frontend.Gnome.EngineAssistantIntroWidget.cs gtk-gui/Smuxi.Frontend.Gnome.EngineAssistantNameWidget.cs gtk-gui/Smuxi.Frontend.Gnome.EngineAssistantConnectionWidget.cs gtk-gui/Smuxi.Frontend.Gnome.EngineAssistantCredentialsWidget.cs Views/Assistants/Engine/EngineAssistantIntroWidget.cs Views/Assistants/Engine/EngineAssistant.cs Views/Assistants/Engine/EngineAssistantNameWidget.cs Views/Assistants/Engine/EngineAssistantConnectionWidget.cs Views/Assistants/Engine/EngineAssistantCredentialsWidget.cs ThemeSettings.cs PangoTools.cs Views/ServerWidget.cs Views/ServerDialog.cs gtk-gui/Smuxi.Frontend.Gnome.ServerDialog.cs gtk-gui/Smuxi.Frontend.Gnome.ServerWidget.cs StatusIconManager.cs gtk-gui/Smuxi.Frontend.Gnome.FilterListWidget.cs Views/FilterListWidget.cs IndicateManager.cs NotifyManager.cs ColorConverter.cs NetworkManager.cs Gtk.WindowExtensions.cs gtk-gui/Smuxi.Frontend.Gnome.JoinWidget.cs Views/JoinWidget.cs osx/IgeMacMenu.cs osx/ApplicationEvents.cs osx/Carbon.cs osx/AppleEvent.cs osx/CoreFoundation.cs gtk-gui/Smuxi.Frontend.Gnome.MenuWidget.cs Views/MenuWidget.cs Views/Tags/LinkTag.cs Views/Tags/PersonTag.cs Views/ChatTreeView.cs Views/Tags/EmojiTag.cs obj/Release/.NETFramework,Version=v4.5.AssemblyAttribute.cs /target:winexe /define:"TRACE;LOG4NET;CONFIG_NINI;GTK_SHARP_2_10;INDICATE_SHARP;NOTIFY_SHARP;IPC_DBUS;DBUS_SHARP" /reference:../../lib/log4net.dll /reference:../../lib/Nini.dll /reference:/usr/lib/mono/4.5/System.dll /reference:/usr/lib/mono/4.5/Mono.Posix.dll /reference:/usr/lib/cli/glib-sharp-2.0/glib-sharp.dll /reference:/usr/lib/cli/glade-sharp-2.0/glade-sharp.dll /reference:/usr/lib/cli/gdk-sharp-2.0/gdk-sharp.dll /reference:/usr/lib/cli/gtk-sharp-2.0/gtk-sharp.dll /reference:/usr/lib/cli/pango-sharp-2.0/pango-sharp.dll /reference:/usr/lib/cli/notify-sharp-0.4/notify-sharp.dll /reference:/usr/lib/gio-sharp/gio-sharp.dll /reference:/usr/lib/cli/atk-sharp-2.0/atk-sharp.dll /reference:/usr/lib/cli/dbus-sharp-1.0/dbus-sharp.dll /reference:/usr/lib/cli/dbus-sharp-glib-1.0/dbus-sharp-glib.dll /reference:/usr/lib/mono/4.5/System.Web.dll /reference:/usr/lib/mono/4.5/System.Core.dll /reference:/home/travis/build/meebey/smuxi/bin/release//smuxi-engine.dll /reference:/home/travis/build/meebey/smuxi/bin/release//smuxi-common.dll /reference:/home/travis/build/meebey/smuxi/bin/release//smuxi-frontend.dll /warn:4
	IndicateManager.cs(28,7): error CS0246: The type or namespace name `Indicate' could not be found. Are you missing an assembly reference?
	IndicateManager.cs(54,9): error CS0246: The type or namespace name `Server' could not be found. Are you missing an assembly reference?
	IndicateManager.cs(55,30): error CS0246: The type or namespace name `Indicator' could not be found. Are you missing an assembly reference?
	IndicateManager.cs(420,51): error CS0246: The type or namespace name `ServerDisplayArgs' could not be found. Are you missing an assembly reference?

indicate-sharp is not available on all Linux distros and even in Ubuntu it needs
to probe for indicate-sharp and messagingmenu-sharp and conditionally use the
available one. This can't be covered in the .csproj file and thus it is better
to remove it for now to fix the CI build.

This change was backported from 1c3473f7173a0c667902a1761b43c8d7ac2d041f of the
master branch.