*.csproj: consistently set TargetFrameworkVersion to v4.7.2 fixing GitHub-CI/build_Ubuntu-latest
The .csproj files contains the TargetFrameworkVersion setting with the
value of v4.5 which is no longer sufficient. The minimum runtime version
of Smuxi is 4.7.2 so we consistently set this version in all .csproj files.

This fixes the xbuild compile error:

	Frontend.cs(192,38): error CS0234: The type or namespace name 'RuntimeInformation' does not exist in the namespace 'System.Runtime.InteropServices' (are you missing an assembly reference?)
				Task "Csc" execution -- FAILED
				Done building target "CoreCompile" in project "/home/runner/work/smuxi/smuxi/src/Frontend-GNOME/Frontend-GNOME.csproj".-- FAILED