Frontend-GNOME: fix NRE thrown in Frontend.Quit()
If starting Smuxi fails and thus _MainWindow hasn't been initialized yet then
calling Quit() throws a NullReferenceException.

	Unhandled Exception:
	System.NullReferenceException: Object reference not set to an instance of an object
	  at Smuxi.Frontend.Gnome.Frontend.Quit () [0x00011] in /home/meebey/Projects/smuxi-stable/src/Frontend-GNOME/Frontend.cs:468
	  at Smuxi.Frontend.Gnome.Frontend.ShowException (Gtk.Window parent, System.Exception ex) [0x00149] in /home/meebey/Projects/smuxi-stable/src/Frontend-GNOME/Frontend.cs:640
	  at Smuxi.Frontend.Gnome.Frontend.ShowException (System.Exception ex) [0x00023] in /home/meebey/Projects/smuxi-stable/src/Frontend-GNOME/Frontend.cs:647
	  at Smuxi.Frontend.Gnome.MainClass.Main (System.String[] args) [0x0026d] in /home/meebey/Projects/smuxi-stable/src/Frontend-GNOME/Main.cs:145