Frontend-GNOME: add missing IntPtr ctors
ProtocolChatView was missing a ctor that receives the raw IntPtr
handle, which was causing the following exception:

GLib.MissingIntPtrCtorException: GLib.Object subclass Smuxi.Frontend.Gnome.ProtocolChatView must provide a protected or public IntPtr ctor to support wrapping of native object handles.
  at GLib.ObjectManager.CreateObject (IntPtr raw) [0x00000] in <filename unknown>:0
  at GLib.Object.GetObject (IntPtr o, Boolean owned_ref) [0x00000] in <filename unknown>:0
  at GLib.Value.op_Explicit (Value val) [0x00000] in <filename unknown>:0
  at GLib.Value.get_Val () [0x00000] in <filename unknown>:0
  at Gtk.TreeStore.GetValue (TreeIter iter, Int32 column) [0x00000] in <filename unknown>:0
  at Smuxi.Frontend.Gnome.ChatTreeView+<FindChatIter>c__AnonStorey27.<>m__42 (TreeModel model, Gtk.TreePath path, TreeIter iter) [0x00004] in /home/knocte/Documents/Code/smuxi/src/Frontend-GNOME/Views/ChatTreeView.cs:388
  at GtkSharp.TreeModelForeachFuncWrapper.NativeCallback (IntPtr model, IntPtr path, IntPtr iter, IntPtr data) [0x00000] in <filename unknown>:0
2013-12-06 22:21:59,165 [Main] DEBUG TRACE - Smuxi.Frontend.Gnome.MainClass.Main()
Smuxi.Frontend.Gnome.Frontend.Init()
Gtk.Application.Run()
Gtk.Application.gtk_main()
GLib.Timeout+TimeoutProxy.Handler()
Gtk.Application+InvokeCB.Invoke()
Smuxi.Frontend.Gnome.GnomeUI+<AddMessageToChat>c__AnonStorey10.<>m__20()
Smuxi.Frontend.Gnome.GnomeUI._AddMessageToChat()
Smuxi.Frontend.Gnome.ChatView.AddMessage()
Smuxi.Frontend.Gnome.MessageTextView.AddMessage()
Smuxi.Frontend.Gnome.MessageTextView.AddMessage()
Smuxi.Frontend.Gnome.MessageTextView.AddMessage()
Smuxi.Frontend.Gnome.ChatView.OnMessageTextViewMessageAdded()
Smuxi.Frontend.Gnome.ChatView.set_HasEvent()
Smuxi.Frontend.Gnome.ChatView.OnStatusChanged()
Smuxi.Frontend.Gnome.MainWindow+<OnChatViewManagerChatAdded>c__AnonStorey1E.<>m__31()
Smuxi.Frontend.Gnome.ChatTreeView.Render()
Smuxi.Frontend.Gnome.ChatTreeView.FindChatIter()
Gtk.TreeStore.Foreach()
Gtk.TreeStore.gtk_tree_model_foreach()
GtkSharp.TreeModelForeachFuncWrapper.NativeCallback()
GLib.ExceptionManager.RaiseUnhandledException()
Smuxi.Frontend.Gnome.Frontend._OnUnhandledException()
Smuxi.Frontend.Gnome.Frontend.ShowException()
Smuxi.Frontend.Gnome.Frontend.ShowException()
Smuxi.Frontend.Gnome.CrashDialog.Run()
Gtk.Dialog.Run()
Gtk.Dialog.gtk_dialog_run()
GLib.Idle+IdleProxy.Handler()
Smuxi.Frontend.Gnome.ChatView.<Sync>m__5B()
Smuxi.Frontend.Gnome.ChatView.OnStatusChanged()
Smuxi.Frontend.Gnome.MainWindow+<OnChatViewManagerChatAdded>c__AnonStorey1E.<>m__31()
Smuxi.Frontend.Gnome.ChatTreeView.Render()
Gtk.TreeStore.SetValue()
Gtk.TreeStore.SetValue()
Gtk.TreeStore.gtk_tree_store_set_value()
GtkSharp.TreeIterCompareFuncWrapper.NativeCallback()
GLib.ExceptionManager.RaiseUnhandledException()
Smuxi.Frontend.Gnome.Frontend._OnUnhandledException()
Smuxi.Common.Trace.CallFull()
Frontend._OnUnhandledException(e = GLib.UnhandledExceptionArgs)
2013-12-06 22:21:59,182 [Main] DEBUG TRACE - [smuxi-frontend-gnome.exe] Frontend.ShowException(ex = GLib.MissingIntPtrCtorException)
2013-12-06 22:21:59,182 [Main] DEBUG TRACE - [smuxi-frontend-gnome.exe] Frontend.ShowException(parent = (null), ex = GLib.MissingIntPtrCtorException)
2013-12-06 22:21:59,182 [Main] ERROR Smuxi.Frontend.Gnome.Frontend - ShowException(): Exception:
GLib.MissingIntPtrCtorException: GLib.Object subclass Smuxi.Frontend.Gnome.ProtocolChatView must provide a protected or public IntPtr ctor to support wrapping of native object handles.
  at GLib.ObjectManager.CreateObject (IntPtr raw) [0x00000] in <filename unknown>:0
  at GLib.Object.GetObject (IntPtr o, Boolean owned_ref) [0x00000] in <filename unknown>:0
  at GLib.Value.op_Explicit (Value val) [0x00000] in <filename unknown>:0
  at GLib.Value.get_Val () [0x00000] in <filename unknown>:0
  at Gtk.TreeStore.GetValue (TreeIter iter, Int32 column) [0x00000] in <filename unknown>:0
  at Smuxi.Frontend.Gnome.ChatTreeView.SortTreeStore (TreeModel model, TreeIter iter1, TreeIter iter2) [0x00004] in /home/knocte/Documents/Code/smuxi/src/Frontend-GNOME/Views/ChatTreeView.cs:272
  at GtkSharp.TreeIterCompareFuncWrapper.NativeCallback (IntPtr model, IntPtr a, IntPtr b, IntPtr user_data) [0x00000] in <filename unknown>:0
make: *** [run-gnome] Error 1