Build, Frontend-*, Server, Engine-MessageBuffer, GitHub-CI/build_Ubuntu-latest: fix duplicate TargetFramework attribute xbuild error
Moved AssemblyTargetFramework definition from AssemblyVersion.cs
to AssemblyTargetFramework.cs and include it only in make-based builds.

xbuild automagically defines the TargetFramework attribute which then leads
to a compile error because of a duplicate attribute definition.

	../AssemblyVersion.cs(49,12): error CS0579: The attribute `System.Runtime.Versioning.TargetFrameworkAttribute' cannot be applied multiple times