Build: change default .NET target version to 4.7.2 (fixes GH-295)
This fixes Debian builds using dpkg-buildpackage as debian/rules overrides the
compiler command with "mono-csc". Thus the default CLI_RUNTIME value will be
set and used in configure.ac, which is "4.5".

Since Frontend-GNOME uses System.Runtime.InteropServices.RuntimeInformation
as of f4f37c70bac1506d590d74b7582b482dff8a3ec6 we need a minimum .NET runtime
version of >= .NET framework 4.7.1 / .NET standard 1.1

Thus bump the default CLI_RUNTIME to 4.7.2, which should fix this compile time
error on Debian:

	...

	Configuration summary for smuxi 1.2.1 (Debian 2:1.2.1+master-1)

	* Installation prefix: /usr
	* Build profile:       debug
	* Compiler:            /usr/bin/mono-csc
	* Target CLI runtime:  4.5

	...

	/usr/bin/mono-csc -define:DEBUG,TRACE,LOG4NET -debug -sdk:4.5 -define:IPC_DBUS -define:DBUS_SHARP -noconfig -codepage:utf8 -warn:4 -optimize- -debug -define:DEBUG "-define:DEBUG,TRACE,LOG4NET,CONFIG_NINI,UI_GNOME,GTK_SHARP_2_8" -win32icon:../../images/icon.ico  -define:GTK_SHARP_2_10 -define:MESSAGING_MENU_SHARP -define:NOTIFY_SHARP -define:GTKSPELL -platform:x86 -out:../../bin/debug/smuxi-frontend-gnome.exe -target:winexe './../AssemblyVersion.cs' './AssemblyInfo.cs' './AboutDialog.cs' './CrashDialog.cs' './EngineManagerDialog.cs' './Entry.cs' './Frontend.cs' './GnomeUI.cs' './Gtk.WindowExtensions.cs' './IndicateManager.cs' './Main.cs' './MainWindow.cs' './NetworkManager.cs' './NotImplementedMessageDialog.cs' './Notebook.cs' './SplashScreenWindow.cs' './ChatTypeWidget.cs' './ChatViewManager.cs' './ColorConverter.cs' './NotifyManager.cs' './PangoTools.cs' './Preferences/ServerListView.cs' './Views/ChatTreeView.cs' './Views/JoinWidget.cs' './Views/MenuWidget.cs' './Views/MessageTextView.cs' './Views/PreferencesDialog.cs' './Views/ServerWidget.cs' './Views/ServerDialog.cs' './Views/FilterListWidget.cs' './Views/Chats/ChatView.cs' './Views/Chats/GroupChatView.cs' './Views/Chats/PersonChatView.cs' './Views/Chats/ProtocolChatView.cs' './Views/Chats/SessionChatView.cs' './Views/Assistants/Engine/EngineAssistantNameWidget.cs' './Views/Assistants/Engine/EngineAssistantCredentialsWidget.cs' './Views/Assistants/Engine/EngineAssistantConnectionWidget.cs' './Views/Assistants/Engine/EngineAssistantIntroWidget.cs' './Views/Assistants/Engine/EngineAssistant.cs' './Views/Tags/EmojiTag.cs' './Views/Tags/LinkTag.cs' './Views/Tags/PersonTag.cs' './QuickConnectDialog.cs' './SteticPreferencesDialog.cs' './FindGroupChatDialog.cs' './ChatFindDialog.cs' './OpenChatDialog.cs' './ThemeSettings.cs' './StatusIconManager.cs' './gtk-gui/generated.cs' './gtk-gui/Smuxi.Frontend.Gnome.EngineAssistantConnectionWidget.cs' './gtk-gui/Smuxi.Frontend.Gnome.EngineAssistantCredentialsWidget.cs' './gtk-gui/Smuxi.Frontend.Gnome.EngineAssistantIntroWidget.cs' './gtk-gui/Smuxi.Frontend.Gnome.EngineAssistantNameWidget.cs' './gtk-gui/Smuxi.Frontend.Gnome.JoinWidget.cs' './gtk-gui/Smuxi.Frontend.Gnome.MenuWidget.cs' './gtk-gui/Smuxi.Frontend.Gnome.OpenChatDialog.cs' './gtk-gui/Smuxi.Frontend.Gnome.SteticPreferencesDialog.cs' './gtk-gui/Smuxi.Frontend.Gnome.QuickConnectDialog.cs' './gtk-gui/Smuxi.Frontend.Gnome.FindGroupChatDialog.cs' './gtk-gui/Smuxi.Frontend.Gnome.ChatFindDialog.cs' './gtk-gui/Smuxi.Frontend.Gnome.ChatTypeWidget.cs' './gtk-gui/Smuxi.Frontend.Gnome.ServerDialog.cs' './gtk-gui/Smuxi.Frontend.Gnome.ServerWidget.cs' './gtk-gui/Smuxi.Frontend.Gnome.FilterListWidget.cs' './osx/AppleEvent.cs' './osx/ApplicationEvents.cs' './osx/Carbon.cs' './osx/CoreFoundation.cs' './osx/IgeMacMenu.cs'  '-resource:./gtk-gui/gui.stetic' '-resource:./../../images/icon_256x256.png' '-resource:./../../images/group-chat_256x256.png' '-resource:./../../images/person-chat_256x256.png' '-resource:./../../images/protocol-chat_256x256.png' '-resource:./../../images/session-chat_256x256.png' '-resource:./Interfaces/PreferencesDialog2.ui' '-resource:./Interfaces/ServerListWidget.ui'    -r:System.Runtime.Remoting    -r:System    -r:System.Core    -r:System.Web    -r:Mono.Posix    -r:/usr/lib/pkgconfig/../../lib/cli/glib-sharp-2.0/glib-sharp.dll    -r:/usr/lib/pkgconfig/../../lib/cli/pango-sharp-2.0/pango-sharp.dll    -r:/usr/lib/pkgconfig/../../lib/cli/atk-sharp-2.0/atk-sharp.dll    -r:/usr/lib/pkgconfig/../../lib/cli/gdk-sharp-2.0/gdk-sharp.dll    -r:/usr/lib/pkgconfig/../../lib/cli/gtk-sharp-2.0/gtk-sharp.dll    -r:/usr/lib/pkgconfig/../../lib/cli/glib-sharp-2.0/glib-sharp.dll    -r:/usr/lib//cli/log4net-1.2/log4net.dll    -r:/usr/lib/cli/messagingmenu-sharp-12.10/messagingmenu-sharp.dll    -r:/usr/lib/pkgconfig/../../lib/gio-sharp/gio-sharp.dll    -r:/usr/lib/pkgconfig/../../lib/cli/glib-sharp-2.0/glib-sharp.dll    -r:/usr/lib/cli/notify-sharp-0.4/notify-sharp.dll    -r:/usr/lib/pkgconfig/../../lib/cli/pango-sharp-2.0/pango-sharp.dll    -r:/usr/lib/pkgconfig/../../lib/cli/atk-sharp-2.0/atk-sharp.dll    -r:/usr/lib/pkgconfig/../../lib/cli/gdk-sharp-2.0/gdk-sharp.dll    -r:/usr/lib/pkgconfig/../../lib/cli/gtk-sharp-2.0/gtk-sharp.dll    -r:/usr/lib/pkgconfig/../../lib/cli/glib-sharp-2.0/glib-sharp.dll    -r:/usr/lib/cli/dbus-sharp-2.0/dbus-sharp.dll    -r:/usr/lib/cli/dbus-sharp-glib-2.0/dbus-sharp-glib.dll    -r:/usr/lib/cli/dbus-sharp-2.0/dbus-sharp.dll   -r:../../bin/debug/smuxi-engine.dll  -r:../../bin/debug/smuxi-common.dll  -r:../../bin/debug/smuxi-frontend.dll
	./Frontend.cs(192,69): error CS0234: The type or namespace name `RuntimeInformation' does not exist in the namespace `System.Runtime.InteropServices'. Are you missing an assembly reference?
	./Views/Chats/ChatView.cs(537,41): warning CS0618: `Smuxi.Engine.ChatModel.Messages' is obsolete: `Use ChatModel.MessageBuffer instead.'
	Compilation failed: 1 error(s), 1 warnings
	make[3]: *** [Makefile:1374 : ../../bin/debug/smuxi-frontend-gnome.exe] Erreur 1
	make[3] : on quitte le répertoire « /root/smuxi-src/smuxi/src/Frontend-GNOME »