Frontend-STFL: fix build on macOS
On macOS the build fails if log4net is bundled instead of provided
via pkg-config like this:

	make[3]: Entering directory '/private/tmp/nix-build-smuxi-1.2.1.drv-0/source/src/Frontend-STFL'
	Makefile:1135: warning: overriding recipe for target '../../bin/debug/smuxi-frontend-stfl.exe.config'
	Makefile:1134: warning: ignoring old recipe for target '../../bin/debug/smuxi-frontend-stfl.exe.config'
	mkdir -p '../../bin/debug'
	cp 'smuxi-frontend-stfl' '../../bin/debug/smuxi-frontend-stfl'
	chmod +x '../../bin/debug/smuxi-frontend-stfl'
	mkdir -p ../../bin/debug/
	cp 'smuxi-frontend-stfl.exe.config' '../../bin/debug/smuxi-frontend-stfl.exe.config'
	make[3]: Circular ../../bin/debug/smuxi-engine.dll <- ../../bin/debug/smuxi-engine.dll dependency dropped.
	make[3]: Circular ../../bin/debug/smuxi-frontend.dll <- ../../bin/debug/smuxi-frontend.dll dependency dropped.
	make[3]: Circular ../../bin/debug/smuxi-common.dll <- ../../bin/debug/smuxi-common.dll dependency dropped.
	mkdir -p ../../bin/debug/
	/nix/store/d442pzvwlaxdi7l7isl9gvzvsqvy21ab-mono-6.12.0.182/bin/mcs -define:DEBUG,TRACE,LOG4NET -debug -sdk:4.7.2 -out:../../bin/debug/smuxi-frontend-stfl.exe -target:exe './Main.cs' './../AssemblyVersion.cs' './../AssemblyTargetFramework.cs' './AssemblyInfo.cs' './Frontend.cs' './MainWindow.cs' './StflUI.cs' './Entry.cs' './STFL/Form.cs' './STFL/EventReceivedEventArgs.cs' './STFL/KeyPressedEventArgs.cs' './STFL/NcursesApi.cs' './STFL/StflApi.cs' './STFL/StringOnHeap.cs' './STFL/TextView.cs' './STFL/Widget.cs' './Views/ChatView.cs' './Views/GroupChatView.cs' './Views/PersonChatView.cs' './ChatViewManager.cs'  '-resource:./MainWindow.stfl'    -r:System    -r:System.Core    -r:Mono.Posix   -r:../../bin/debug/smuxi-engine.dll  -r:../../bin/debug/smuxi-frontend.dll  -r:../../bin/debug/smuxi-common.dll
	./Main.cs(39,33): error CS0246: The type or namespace name `log4net' could not be found. Are you missing an assembly reference?
	./Frontend.cs(36,33): error CS0246: The type or namespace name `log4net' could not be found. Are you missing an assembly reference?
	./MainWindow.cs(36,25): error CS0246: The type or namespace name `log4net' could not be found. Are you missing an assembly reference?
	./StflUI.cs(32,33): error CS0246: The type or namespace name `log4net' could not be found. Are you missing an assembly reference?
	./Entry.cs(37,33): error CS0246: The type or namespace name `log4net' could not be found. Are you missing an assembly reference?
	./STFL/TextView.cs(32,25): error CS0246: The type or namespace name `log4net' could not be found. Are you missing an assembly reference?
	./Views/ChatView.cs(40,25): error CS0246: The type or namespace name `log4net' could not be found. Are you missing an assembly reference?
	./ChatViewManager.cs(38,33): error CS0246: The type or namespace name `log4net' could not be found. Are you missing an assembly reference?
	Compilation failed: 8 error(s), 0 warnings
	make[3]: *** [Makefile:1146: ../../bin/debug/smuxi-frontend-stfl.exe] Error 1