Build: include libMonoPosixHelper.so for Linux static builds
The shared library libMonoPosixHelper.so is required by the smuxi-server
application but it isn't automatically bundled by mkbundle. So starting
smuxi-server crashes like this without the library:

    $ ./smuxi-server --help

    Unhandled Exception:
    System.TypeInitializationException: The type initializer for 'Mono.Unix.Native.Stdlib' threw an exception. ---> System.DllNotFoundException: /usr/lib/libMonoPosixHelper.so
      at (wrapper managed-to-native) Mono.Unix.Native.Stdlib:GetDefaultSignal ()
      at Mono.Unix.Native.Stdlib..cctor () [0x00006] in <34b68016c17845bba60316001d489522>:0
       --- End of inner exception stack trace ---
      at Mono.Unix.UnixMarshal.AllocHeap (System.Int64 size) [0x00018] in <34b68016c17845bba60316001d489522>:0
      at Mono.Unix.UnixMarshal.StringToHeap (System.String s, System.Int32 index, System.Int32 count, System.Text.Encoding encoding) [0x00061] in <34b68016c17845bba60316001d489522>:0
      at Mono.Unix.UnixMarshal.StringToHeap (System.String s, System.Text.Encoding encoding) [0x00008] in <34b68016c17845bba60316001d489522>:0
      at Mono.Unix.UnixMarshal.StringToHeap (System.String s) [0x00000] in <34b68016c17845bba60316001d489522>:0
      at Mono.Unix.Catalog.MarshalStrings (System.String s1, System.IntPtr& p1, System.String s2, System.IntPtr& p2, System.String s3, System.IntPtr& p3) [0x00014] in <34b68016c17845bba60316001d489522>:0
      at Mono.Unix.Catalog.Init (System.String package, System.String localedir) [0x00000] in <34b68016c17845bba60316001d489522>:0
      at Smuxi.Common.LibraryCatalog.Init (System.String textDomain, System.String localeDirectory) [0x0000c] in <a860ef0516d443d2b982e538c4ad073f>:0
      at Smuxi.Server.MainClass.InitLocale () [0x00046] in <29bc06fe56694183a62fafab6d86b66e>:0
      at Smuxi.Server.MainClass.Main (System.String[] args) [0x0005f] in <29bc06fe56694183a62fafab6d86b66e>:0

To fix the application crash, the dist-linux-static is now copying the shared
library into the static smuxi-server tarball for Linux.