Engine-Twitter: handle IOException inner-exceptions
Twitter has every day IOExceptions thus they need to be treated like temporary
issues and not permanent issue.

Example:

    2021-01-20 05:08:54,628 [TwitterProtocolManager friends timeline listener] ERROR Smuxi.Engine.TwitterProtocolManager - UpdateFriendsTimelineThread(): Exception

    System.Net.WebException: Unable to read data from the transport connection: Connection reset by peer. ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer. ---> System.Net.Sockets.SocketException: Connection reset by peer

      at Smuxi.Engine.TwitterProtocolManager.CheckWebException (System.Net.WebException exception) [0x0008d] in <b07886f794b444e6a88ef1ae4c9ed942>:0