GitHub-CI/build_Ubuntu-latest: install nunit-console
Fix "make test" by installing missing nunit-console.

	cd ./bin/debug; \
	  for TEST_ASSEMBLY in \
	    smuxi-common-tests.dll \
	    smuxi-engine-tests.dll \
	    smuxi-frontend-tests.dll \
	    smuxi-frontend-gnome-tests.dll \
	    smuxi-frontend-stfl-tests.dll; do \
	      nunit-console $TEST_ASSEMBLY; \
	done
	/bin/bash: line 8: nunit-console: command not found
	/bin/bash: line 8: nunit-console: command not found
	/bin/bash: line 8: nunit-console: command not found
	/bin/bash: line 8: nunit-console: command not found
	/bin/bash: line 8: nunit-console: command not found
	make: *** [Makefile:1179: test] Error 127
	Error: Process completed with exit code 2.